### ISSUE TITLE
Update workflow glsp code to align with rework in GLSP examples

### ISSUE THREAD

**Issue by lucas-koehler** [eclipse-emfcloud/coffee-editor#361]
The workflow example was simplified with https://github.com/eclipse-glsp/glsp/issues/220 . This simplification should also be applied to the coffee editor.

**Comment by eneufeld** [comment]
@lucas-koehler with the merge of https://github.com/eclipse-emfcloud/coffee-editor/pull/419 this should be fixed? Or is there still an update needed?

**Comment by lucas-koehler** [comment]
@eneufeld No, https://github.com/eclipse-emfcloud/coffee-editor/pull/419 does not fix this. It still needs to be manually fixed here because the workflow example is not imported from GLSP but the coffee editor has its own GLSP workflow packages (`coffee-workflow-glsp-editor` and `coffee-workflow-sprotty` in the frontend and glsp plugins in the backend).

**Comment by eneufeld** [comment]
This was updated with #424
